apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod2
  labels:
    app: mysql-pod2
spec:
  containers:
    - name: mysql-pod2
      image: mysql:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: MYSQL_DATABASE
          value: "mydb"
        - name: MYSQL_USER
          value: "moahmed"
        - name: MYSQL_ROOT_PASSWORD
          value: "mysecretpassword"
      ports:
        - containerPort: 3306